name: Reservation Service Mutation Flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: Install dependencies
        run: dotnet tool restore --tool-manifest ./Services/ReservationService/.config/dotnet-tools.json
      - name: Run Mutations
        env:
          STRYKER_DASHBOARD_API_KEY: ${{secrets.STRYKER_DASHBOARD_API_KEY }}

        run: cd ./Services/ReservationService/tests/ReservationService.Application.UnitTests/ && dotnet stryker
